### ISSUE TITLE
how to train on my own database?

### ISSUE THREAD

**Issue by manvirvirk** [nibtehaz/MultiResUNet#10]
i want to train this on my own database.

**Comment by nibtehaz** [comment]
Hi, thanks for your interest in our project. To train this on your data please follow this Jupyter Notebook

https://github.com/nibtehaz/MultiResUNet/blob/master/Demo.ipynb

Here we have trained the model on ISIC 2017 dataset, but the complete pipeline is demonstrated. Just replace your data with the data we used.

Hope this helps, have a good day.

**Comment by manvirvirk** [comment]
Hi, thanks for the help. I have database of  few images and corresponding
masks. I could not get your database directory. Please explain in which
folder i have to place my data and which file is used to train and test the
model.
Thanks

**Comment by nibtehaz** [comment]
Hello, apologies for missing this issue, I haven't been much active lately.

You don't need to worry about database directory much. Just load the images and masks as numpy array as you would for any keras model and use the multiresunet keras model to train / predict.

Hope this helps, sorry again for such a late reply.
