### ISSUE TITLE
Request for Environment requirements

### ISSUE THREAD

**Issue by csrvictory** [nibtehaz/MultiResUNet#13]
Dear sir
Plz provide Environments requirements

**Comment by nibtehaz** [comment]
Hello, thank you for your interest in our multiresunet project. I am sorry for my delayed response as I have not been active lately.

There is not any specific environment requirements. But our experiments were performed using the following versions

tensorflow-gpu==1.5.0
Keras==2.2.4

Again I apologize for the delayed response.

**Comment by csrvictory** [comment]
Thank you very much, 
your work is excellent.

You are spreading knowledge through this platform, no need of apologies.

**Comment by nibtehaz** [comment]
Thank you @csrvictory  , that's so kind of you. Best wishes :)
