### ISSUE TITLE
version of the network

### ISSUE THREAD

**Issue by qianqianCDQ** [nibtehaz/MultiResUNet#14]
Hello, can you provide the pytorch version of the network implementation code, I tried to reproduce your MultiResUnet code here, but problems continue to occur, thank you

**Comment by nibtehaz** [comment]
Hello, thank you for your interest in our multiresunet project. I am sorry for my delayed response as I have not been active lately.

Unfortunately, currently we have not make any implementation of the model in pytorch. If we do so in the future I'll update you here.

Again I apologize for the delayed response.

**Comment by nibtehaz** [comment]
Hi, we have the pytorch implementation now in the repo
