### ISSUE TITLE
Use of trans_conv2d_bn

### ISSUE THREAD

**Issue by andrealpkth** [nibtehaz/MultiResUNet#17]
Hi,

Thank you very much for your work. I'm trying to implement the MultiResUNet as a generator of a GAN. I would like to know if the definition of trans_conv_2d has any purpose since it is not used. Also, why did you decide not to use dropout?

Thanks!

**Comment by nibtehaz** [comment]
Hi @andrealpkth 

Thank you for your interest in our project.

I was experimenting first with trans_conv_2d but in my experiments it didn't help that  much, so I later moved on to the standard Conv2DTranspose. Same for dropout, it didn't help that much (or for my particular experiments I couldn't explore it enough). 

But feel free to experiment with them in your task. Best wishes.

**Comment by andrealpkth** [comment]
Thank you very much.
