### ISSUE TITLE
Demo for the ISBI 2012 challenge dataset

### ISSUE THREAD

**Issue by scalemailted** [nibtehaz/MultiResUNet#24]
In your paper, it appears that you tested this implementation using the ISBI 2012 challenge dataset - Electron Microscopy Image. 
Do you have a sample demo notebook you could share?

**Comment by Shihang-Li1** [comment]
https://isic-challenge-data.s3.amazonaws.com/2017/ISIC-2017_Training_Data.zip
If you have difficulty for downloading the dataset, this is the new link for that. Rest of the part works for me.

**Comment by scalemailted** [comment]
Thank you so much!
