### ISSUE TITLE
Any Pytorch implementation? 

### ISSUE THREAD

**Issue by alqurri77** [nibtehaz/MultiResUNet#25]
Hi;

This is not an issue, but I was wondering if there any Pytorch implementation of your model.

Thank you!

**Comment by nibtehaz** [comment]
Hello, sorry I haven't done any PyTorch implementation myself. But I believe there are some PyTorch implementations of our model.

**Comment by PatrickWilliams44** [comment]
Hi! Have you completed the reproduction of the pytorch version?@alqurri77

**Comment by nibtehaz** [comment]
Hi, we have the pytorch implementation now in the repo
