### ISSUE TITLE
About pytorch version

### ISSUE THREAD

**Issue by PatrickWilliams44** [nibtehaz/MultiResUNet#26]
Hi! It is a great honor to see your research paper "MultiResUNet : Rethinking the U-Net Architecture for Multimodal Biomedical Image Segmentation". Now I want to reproduce the corresponding code of the paper. Can you provide the pytorch version of the code?

**Comment by nibtehaz** [comment]
Hi Patrick, thank you so much for your kind words. Unfortunately, I didn't implemented this model in pytorch. If I do I will let you know.

But there are some pytorch implementation of the model in github, you may use them.

Best wishes 😊

**Comment by nibtehaz** [comment]
Hi, we have the pytorch implementation now in the repo

**Comment by PatrickWilliams44** [comment]
Hello! Thank you very much for your tireless efforts and for providing the pytorch version of the application. Gratitude, beyond words!


On 10/22/2022 11:56，Nabil ***@***.***> wrote：

Hi, we have the pytorch implementation now in the repo
