### ISSUE TITLE
About the ISIC-17 Dataset download link in the demo

### ISSUE THREAD

**Issue by PatrickWilliams44** [nibtehaz/MultiResUNet#27]
Hi! It is an honor to read your paper "MultiResUNet : Rethinking the U-Net Architecture for Multimodal Biomedical Image Segmentation", and now I want to reproduce the code corresponding to the paper. Unfortunately, the ISIC-17 Dataset download link provided in your demo doesn't seem to work,How should I solve this problem?
Words fail me when I wish to express my sincere gratitude to you.Looking forward to your early reply!

**Comment by nibtehaz** [comment]
Hi, thank you so much for your kind words. I am very delighted that you feel that way.

It appears that the ISIC community has a new website for their dataset. Please try this link 

https://challenge.isic-archive.com/data/

**Comment by PatrickWilliams44** [comment]
Hi,thank you very much for your reply, I will continue my research on the ISIC-17 dataset you provided. 
The gratitude is beyond words. Thank you again.
