### ISSUE TITLE
ValueError: logits and labels must have the same shape ((None, 192, 256, 3) vs (None, 192, 256, 1))

### ISSUE THREAD

**Issue by hendriramdan** [nibtehaz/MultiResUNet#28]
i am trying to use this architecture for multiclass segmentation by replacing conv10 = conv2d_bn(mresblock9, 3, 1, 1, activation='sigmoid') to conv10 = conv2d_bn(mresblock9, 1, 1, 1, activation='sigmoid') with dataset like this
![image](https://user-images.githubusercontent.com/43942980/182357556-17e1bd4b-11a1-4390-9571-0b5e8dde2a26.png)
but i get error :  ValueError: Input 0 of layer conv2d_115 is incompatible with the layer: expected axis -1 of input shape to have value 1 but received input with shape (None, 192, 256, 3)
my question is.
1. is it enough just to change the number 1 to number 3 in the section conv10 = conv2d_bn(mresblock9, 1, 1, 1, activation='sigmoid')?
2. does the activation function still use sigmoid?
3.  does the loss function still use binary_crossentropy?

thank

**Comment by nibtehaz** [comment]
Hi, based on your post and our previous mail communication, do you mean ?

replacing conv10 = conv2d_bn(mresblock9, 3, 1, 1, activation='sigmoid') to conv10 = conv2d_bn(mresblock9, 1, 1, 1, activation='sigmoid')

or replacing conv10 = conv2d_bn(mresblock9, 1, 1, 1, activation='sigmoid') to conv10 = conv2d_bn(mresblock9, 3, 1, 1, activation='sigmoid')?

for the valueError, can you please share the code? As it is a bit difficult to understand the layer conv2d_115

1. Yes, but you may consider a different activation
2. I would suggest using softmax instead , as this is not multilabel dataset
3. The best option would be to use dice loss.

You may study this repo to see how to handle multiclass cases

https://github.com/cm-amaya/UNet_Multiclass/blob/master/main.py

**Comment by tphankr** [comment]
Thank you @nibtehaz and @hendriramdan,
Dear @hendriramdan , did you do with multi-classes? Can you share?
Dar @nibtehaz, Do you have any other reference/ github because I followed the link which u shared above but can not finish yet. Thanks.

**Comment by nibtehaz** [comment]
Hi @tphankr , what error are you getting? Maybe I can suggest something based on that.
