### ISSUE TITLE
First convolution layers in MultiResUBlock and ResPath don't use any activations

### ISSUE THREAD

**Issue by cloudscapes** [nibtehaz/MultiResUNet#7]
Hi there, 

I'm about to experiment and use a modified version of your architecture in my master's thesis. I saw in your code that the first convolution layers in MultiResUBlock and ResPath don't use any activation function. What was the reason you decided not to use an activation function here ???

> shortcut = conv2d_bn(shortcut, filters, 1, 1,activation=None, padding='same')

Cheers, 
H

**Comment by nibtehaz** [comment]
Hi @cloudscapes  , pardon me for this delayed response. I'm really delighted to hear that MultiResUNet will be useful for your master's thesis.

About using no activation functions, those layers are actually for shortcut connections. They are there to just keep the dimensions matched, hence there is no activation function.

You may refer to the keras official implementation of ResNet50 architectures, you'll see that they also have no activations. 


https://github.com/keras-team/keras-applications/blob/976050c468ff949bcbd9b9cf64fe1d5c81db3f3a/keras_applications/resnet50.py#L130

Same can be seen in the other official ResNet implementations from the keras library

https://github.com/keras-team/keras-applications/blob/master/keras_applications/resnet_common.py

I've just followed the standard ResNet architecture in my work. However, it may be interesting to see what the outcome becomes if these shortcut layers are also nonlinearly activated. And, I'm not sure there may be some works exploring that as well.

Hope this helps, please let me know if I can aid you with anything else. Have a great day.

**Comment by cloudscapes** [comment]
Thank you so much for getting back, 

> shortcut connection... are there to just keep the dimensions matched, hence there is no activation function.

Indeed! You are right! 

> what the outcome becomes if these shortcut layers are also nonlinearly activated.

I'm also curious to see what the outcome would be. I am applying your architecture not to image processing but to audio(musical signals). Another question I have is that as long as I'm using a filter size that is a multiple of 16, for example, calling ` model = MultiResUnet(128, 128,3)
 display(model.summary()) ` everything works just as expected and Tenorflow shows me a nice summary. BUT when I change the filter size to anything that is not a multiple of 16, for example, 
`model = MultiResUnet(36, 36,3)
 display(model.summary()) ` the output of the transposed Conv has always one spatial dimension less (height and width) than the "mresblock" and hence the Concat function complains and outputs this error 

> ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 8, 8, 128), (None, 9, 9, 128)]

How can I overcome these filter size issues? how can I make this system work with any filter dimension? It seems that if the filter size is not a multiple of 16, the output of the Transposed Conv layer has always one dimension less than the mresblock that the Concat function wants to concatenate it with. 

And again thank you so much for answering my question. 
Cheers, 
H

**Comment by nibtehaz** [comment]
Hi, thank you for your appreciation.

About your question of dimension mismatch, what happens for UNet like architectures that when we do pooling dimension is divided by 2, and when we do upsampling or transposed convolution it gets multiplied by 2. So if the dimensions are not powers of 2, then you'll lose the remainders while dividing. Obviously you can change the division and multiplication factor to another number say 'k', but in that case the dimension needs to be a power of k. 

Also as I'm saying power of 2, it doesn't necessarily need to be. Say you have 5 pooling and later 5 upsampling layers, so you need your dimensions to be 2^5 but if it is a multiple of 2^5 it will be just fine, say for example 3*2^5= 96. So the pooling divides the dimensions as 96>48>24>12>6>3 , then the transposed convolution changes it to 3>6>12>24>48>96. So you can see that dimensions are preserved.

I understand your requirements, maybe you are working with spectrogram so your input is 36x36. You can do one of the following, you may make the network shallower by removing some layers, or you can pad your input with zeroes, or you can change the stride to 1 in pooling and change transconvolution layers to merely conv layers (this will be weird, need more memory and not recommended).

**Comment by Ayanzadeh93** [comment]
@nibtehaz I have a specific question about respath, why you use 1x1 convolution in the respath. As I know 1x1 convolution is applied whenever we want to reduce or increase the depth dimension of the channel in the convolution. bu the number of input feature does not change during the convolution.

**Comment by nibtehaz** [comment]
Hi @Ayanzadeh93  , yes you are right we need 1x1 convolutions to control the dimensions when they are not equal. They were kept here if we wished to experiment with different dimensions. Just for an extension nothing else.
