### ISSUE TITLE
/bin/sh: 1: unzip: not found

### ISSUE THREAD

**Issue by Laura1295** [nibtehaz/MultiResUNet#9]
When I'm running the Demo notebook, I get this when I run the code block of extracting the zip files.

Does anyone know how to fix this? Thanks!

(p.s. I am a beginner in python)

**Comment by nibtehaz** [comment]
Hi @Laura1295 , sorry for the late response. This error is most likely indicating that you don't have unzip installed in your pc. Please install that and try again. Or alternatively you can unzip it using some other tool and then omit that instruction.

Hope this helps, have a great day.
